from collections.abc import Iterable, Mapping, Sequence
from typing import overload

class Basic:
    args: tuple[Basic, ...]
    is_Mul: bool
    is_positive: bool | None
    @property
    def free_symbols(self) -> set[Symbol]: ...
    def __add__(self, other: object) -> Expr: ...
    def __radd__(self, other: object) -> Expr: ...
    def __sub__(self, other: object) -> Expr: ...
    def __rsub__(self, other: object) -> Expr: ...
    def __mul__(self, other: object) -> Expr: ...
    def __rmul__(self, other: object) -> Expr: ...
    def __truediv__(self, other: object) -> Expr: ...
    def __rtruediv__(self, other: object) -> Expr: ...
    def __pow__(self, other: object) -> Expr: ...
    def __rpow__(self, other: object) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def subs(self, old: Basic, new: Basic) -> Basic: ...
    def as_ordered_factors(self) -> list[Basic]: ...
    def has(self, pattern: Basic) -> bool: ...
    def __str__(self) -> str: ...

class Expr(Basic): ...
class Equality(Basic):
    lhs: Basic
    rhs: Basic
class Symbol(Expr):
    name: str
    def __new__(cls, name: str, **assumptions: bool) -> Symbol: ...
class Integer(Expr):
    def __new__(cls, value: int | str) -> Integer: ...
class Rational(Expr):
    def __new__(cls, numerator: int | str, denominator: int = ...) -> Rational: ...
class Float(Expr):
    def __new__(cls, value: str | float, precision: int = ...) -> Float: ...
class FunctionClass:
    def __call__(self, *args: Basic) -> Expr: ...
def Function(name: str) -> FunctionClass: ...
class Poly:
    def __new__(cls, expression: Basic, variable: Symbol) -> Poly: ...
    def degree(self) -> int: ...
    def coeff_monomial(self, monomial: Basic | int) -> Basic: ...
    def as_expr(self) -> Basic: ...
class PolynomialError(Exception): ...
class MatrixBase:
    rows: int
    cols: int
    def __getitem__(self, key: tuple[int, int]) -> Basic: ...
    def det(self) -> Basic: ...
    def inv(self) -> MatrixBase: ...
    def rank(self) -> int: ...
    def rref(self) -> tuple[MatrixBase, tuple[int, ...]]: ...
    def eigenvals(self) -> Mapping[Basic, int]: ...
class Matrix(MatrixBase):
    def __new__(cls, rows: Sequence[Sequence[Basic]]) -> Matrix: ...

pi: Expr
E: Expr
I: Expr
oo: Expr
nan: Expr
zoo: Expr
true: Basic
false: Basic

def Add(*args: Basic, evaluate: bool = ...) -> Expr: ...
def Mul(*args: Basic, evaluate: bool = ...) -> Expr: ...
def Pow(base: Basic, exponent: Basic | int, evaluate: bool = ...) -> Expr: ...
def Eq(left: Basic, right: Basic | int, evaluate: bool = ...) -> Equality: ...
def Ne(left: Basic, right: Basic) -> Basic: ...
def Lt(left: Basic, right: Basic) -> Basic: ...
def Le(left: Basic, right: Basic) -> Basic: ...
def Gt(left: Basic, right: Basic) -> Basic: ...
def Ge(left: Basic, right: Basic) -> Basic: ...
def sin(value: Basic) -> Expr: ...
def cos(value: Basic) -> Expr: ...
def tan(value: Basic) -> Expr: ...
def asin(value: Basic) -> Expr: ...
def acos(value: Basic) -> Expr: ...
def atan(value: Basic) -> Expr: ...
def sinh(value: Basic) -> Expr: ...
def cosh(value: Basic) -> Expr: ...
def tanh(value: Basic) -> Expr: ...
def exp(value: Basic) -> Expr: ...
def log(value: Basic, base: Basic | None = ...) -> Expr: ...
def sqrt(value: Basic) -> Expr: ...
def Abs(value: Basic) -> Expr: ...
def factorial(value: Basic) -> Expr: ...
def gamma(value: Basic) -> Expr: ...
def simplify(value: Basic) -> Basic: ...
def expand(value: Basic) -> Basic: ...
def factor(value: Basic) -> Basic: ...
def together(value: Basic) -> Basic: ...
def fraction(value: Basic) -> tuple[Basic, Basic]: ...
def cancel(value: Basic) -> Basic: ...
def apart(value: Basic, variable: Basic | None = ...) -> Basic: ...
def diff(value: Basic, variable: Basic, order: int = ...) -> Basic: ...
def integrate(value: Basic, *variables: object) -> Basic: ...
def limit(value: Basic, variable: Basic, point: Basic, direction: str = ...) -> Basic: ...
def series(value: Basic, variable: Basic, point: Basic, order: int) -> Basic: ...
def summation(value: Basic, limits: tuple[Basic, Basic, Basic]) -> Basic: ...
def product(value: Basic, limits: tuple[Basic, Basic, Basic]) -> Basic: ...
def solve(expression: Basic | Sequence[Basic], *symbols: Basic, dict: bool = ...) -> object: ...
def solve_univariate_inequality(expression: Basic, symbol: Symbol) -> Basic: ...
def dsolve(expression: Basic, function: Basic) -> Basic: ...
def rsolve(expression: Basic, function: Basic) -> Basic: ...
def laplace_transform(value: Basic, variable: Basic, frequency: Basic, noconds: bool = ...) -> object: ...
def inverse_laplace_transform(value: Basic, frequency: Basic, variable: Basic) -> Basic: ...
def fourier_transform(value: Basic, variable: Basic, frequency: Basic) -> Basic: ...
def inverse_fourier_transform(value: Basic, frequency: Basic, variable: Basic) -> Basic: ...
def gcd(left: Basic, right: Basic) -> Basic: ...
def lcm(left: Basic, right: Basic) -> Basic: ...
def isprime(value: int) -> bool: ...
def factorint(value: int) -> dict[int, int]: ...
def binomial(n: Basic, k: Basic) -> Basic: ...
def N(value: Basic, digits: int = ...) -> Basic: ...
